name: Deploy Apache Web Server

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'public/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Apache
        run: |
          sudo apt-get update
          sudo apt-get install -y apache2

      - name: Clean Apache root
        run: sudo rm -rf /var/www/html/*

      - name: Copy site files to Apache root
        run: |
          sudo cp -r public/* /var/www/html/
          sudo chown -R www-data:www-data /var/www/html/

      - name: Reload Apache
        run: sudo systemctl reload apache2

      - name: Verify Apache is serving the site
        run: curl -I http://localhost | grep "200 OK"